on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test variables

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env: 
          RMD_PATH: ($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
        run: echo $RMD_PATH
      
      - name: test
        run: echo $RMD_PATH
        
      - name: test2
        run: echo $RMD_PATH
