on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test variables

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: RMD_PATH='hello world'
      - name: test2
        run: echo $RMD_PATH
